#!/usr/bin/env node
// Generates the Homebrew formula for a released version.
//
// The formula points at the archives already attached to a GitHub Release and
// embeds their checksums, so `brew install` verifies the same bytes
// `install.sh` and the npm packages carry. Nothing is rebuilt.
//
// # Usage
//
//   node homebrew/formula.mjs 0.2.1              # fetches SHA256SUMS from the release
//   node homebrew/formula.mjs 0.2.1 --sums <file>
//   node homebrew/formula.mjs 0.2.1 --out Formula/kosong.rb
//
// Writes to stdout unless --out is given.
//
// # Where the output goes
//
// A Homebrew tap must be its own repository named `homebrew-<something>`, so
// this file cannot put the formula where it needs to live. See
// homebrew/README.md for the three ways of getting it there and what each
// costs.

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const REPO = 'khalilhimura/kosong';

// Rust triple to the Homebrew block it belongs in. Same four targets
// `npm/build.mjs` publishes; a release that grows a target needs a row here
// too, and `brew audit` will not notice one missing.
const TARGETS = [
  { triple: 'aarch64-apple-darwin', os: 'macos', cpu: 'arm' },
  { triple: 'x86_64-apple-darwin', os: 'macos', cpu: 'intel' },
  { triple: 'aarch64-unknown-linux-gnu', os: 'linux', cpu: 'arm' },
  { triple: 'x86_64-unknown-linux-gnu', os: 'linux', cpu: 'intel' },
];

function parseArgs(argv) {
  const options = { version: null, sums: null, out: null };
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === '--sums') options.sums = argv[++i];
    else if (argv[i] === '--out') options.out = argv[++i];
    else if (!options.version) options.version = argv[i];
    else throw new Error(`unexpected argument: ${argv[i]}`);
  }
  if (!options.version) throw new Error('usage: formula.mjs <version> [--sums <file>] [--out <file>]');
  return options;
}

/// The checksum manifest, from a file or from the release it describes.
function readSums(version, file) {
  if (file) return fs.readFileSync(file, 'utf8');

  const url = `https://github.com/${REPO}/releases/download/v${version}/SHA256SUMS`;
  const result = spawnSync('curl', ['-fsSL', url], { encoding: 'utf8' });
  if (result.status !== 0) {
    throw new Error(`could not fetch ${url}\nIs v${version} released?`);
  }
  return result.stdout;
}

/// Maps archive name to checksum, and insists every target is present.
///
/// A formula missing a platform is not a formula that fails to build — it is
/// one that installs on three platforms and tells the fourth that kosong is
/// unavailable, which is a worse thing to publish.
function checksums(version, sums) {
  const table = new Map();
  for (const line of sums.split('\n')) {
    const match = line.trim().match(/^([0-9a-f]{64})\s+\*?(\S+)$/);
    if (match) table.set(match[2], match[1]);
  }

  return TARGETS.map((target) => {
    const archive = `kosong-${version}-${target.triple}.tar.gz`;
    const sha256 = table.get(archive);
    if (!sha256) {
      throw new Error(`SHA256SUMS has no entry for ${archive}`);
    }
    return {
      ...target,
      url: `https://github.com/${REPO}/releases/download/v${version}/${archive}`,
      sha256,
    };
  });
}

function block(entries, os) {
  const lines = [];
  for (const cpu of ['arm', 'intel']) {
    const entry = entries.find((e) => e.os === os && e.cpu === cpu);
    lines.push(
      `    on_${cpu} do`,
      `      url "${entry.url}"`,
      `      sha256 "${entry.sha256}"`,
      '    end',
    );
  }
  return lines.join('\n');
}

function formula(version, entries) {
  return `# typed: false
# frozen_string_literal: true

# Generated by homebrew/formula.mjs in khalilhimura/kosong. Do not edit by
# hand: regenerate it for the version being released.
class Kosong < Formula
  desc "Open a terminal. Write one page. Publish it. Learn what happened"
  homepage "https://kosong.thefutureissolo.com"
  version "${version}"
  license "Apache-2.0"

  on_macos do
${block(entries, 'macos')}
  end

  on_linux do
${block(entries, 'linux')}
  end

  def install
    bin.install "kosong"
  end

  test do
    assert_match "kosong #{version}", shell_output("#{bin}/kosong --version")

    # A CLI that starts and cannot make a file has not been tested.
    system bin/"kosong", "--workspace", testpath, "new", "--title", "Brew Test"
    assert_path_exists testpath/"kosong.md"
  end
end
`;
}

function main() {
  const { version, sums, out } = parseArgs(process.argv.slice(2));
  const entries = checksums(version, readSums(version, sums));
  const text = formula(version, entries);

  if (out) {
    fs.mkdirSync(path.dirname(path.resolve(ROOT, out)), { recursive: true });
    fs.writeFileSync(path.resolve(ROOT, out), text);
    console.error(`wrote ${out} for ${version}`);
  } else {
    process.stdout.write(text);
  }
}

try {
  main();
} catch (error) {
  process.stderr.write(`\nCould not generate the formula: ${error.message}\n\n`);
  process.exit(1);
}
